FROM nvcr.io/nvidia/cuda:11.5.0-runtime-ubuntu18.04

# INSTALL TENSORRT
RUN apt update && \
	apt install -y wget &&\
	mkdir -p trt && \
	cd trt && \
	wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libnvinfer8_8.2.3-1+cuda11.4_amd64.deb --no-check-certificate && \
	wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libnvinfer-plugin8_8.2.3-1+cuda11.4_amd64.deb --no-check-certificate && \
	wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libnvonnxparsers8_8.2.3-1+cuda11.4_amd64.deb --no-check-certificate && \
	wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libnvparsers8_8.2.3-1+cuda11.4_amd64.deb --no-check-certificate && \
	wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/libcudnn8_8.3.2.44-1+cuda11.5_amd64.deb --no-check-certificate && \
	dpkg -i *.deb
